allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - brace-expansion@1.1.16
  - brace-expansion@5.0.7
  - js-yaml@4.3.0
  - body-parser@2.3.0
  - hono@4.12.27
  - fast-uri@3.1.4
  - brace-expansion@1.1.17
  - brace-expansion@5.0.8
  - postcss@8.5.23
  - fast-uri@3.1.5
  - ip-address@10.3.1
  - ip-address@10.2.2
  - ip-address@10.2.1
  - hono@4.12.34
  - brace-expansion@5.0.9
  - brace-expansion@1.1.18
  - js-yaml@4.3.1
  - '@hono/node-server@1.19.15'
  - postcss@8.5.18
  - fast-uri@3.1.3
